[package]
name = "impala"
version = "0.2.1"
authors = ["Badr Badri <contact@pythops.com>"]
license = "GPL-3.0"
edition = "2021"
description = "TUI for managing wifi"
readme = "Readme.md"
homepage = "https://github.com/pythops/impala"
repository = "https://github.com/pythops/impala"

[dependencies]
async-channel = "2"
crossterm = { version = "0.27", default-features = false, features = [
  "event-stream",
] }
ratatui = "0.27"
tui-input = "0.8"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
dirs = "5"
serde = { version = "1", features = ["derive"] }
toml = { version = "0.8" }
clap = { version = "4", features = ["derive", "cargo"] }
terminal-light = "1"
anyhow = "1"
iwdrs = "0.1"
chrono = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-error = "0.2"

[profile.release]
strip = true
