[package]
name = "impala"
version = "0.1.0"
authors = ["pythops <contact@pythops.com>"]
license = "GPL-3.0"
edition = "2021"
description = "TUI for managing wifi."
readme = "Readme.md"
homepage = "https://github.com/pythops/impala"
repository = "https://github.com/pythops/impala"

[dependencies]
async-channel = "2"
crossterm = { version = "0.27.0", features = ["event-stream"] }
ratatui = "0.26.3"
tui-input = "0.8"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
dirs = "5"
serde = { version = "1", features = ["derive"] }
toml = { version = "0.8" }
clap = { version = "4", features = ["derive", "cargo"] }
terminal-light = "1"
anyhow = "1"
iwdrs = "0.1"

[profile.release]
strip = true
